# ================================================
# config.yaml
# 
# This file contains configuration data
# such as API keys, credentials, and URLs required
# for the timetable_scraper project.
# 
# =================================================

# --------------------------------------------
# OpenAI API Configuration
# --------------------------------------------
# OpenAI API key for parsing timetable event details.
# Obtain your API key from https://platform.openai.com/account/api-keys
openai:
  api_key: ""  # Replace with your OpenAI API key

# --------------------------------------------
# WebDAV and Timetables Configuration
# --------------------------------------------
webdav:
  credentials:
    username: ""  # Replace with your WebDAV username
    password: ""  # Replace with your WebDAV password

  # Timetables configuration (URLs, keywords, and associated Google Calendar IDs)
  timetables:
    timetable_1:
      url: "https://nbl.hsbi.de/elearning/webdav.php/FH-Bielefeld/ref_155901"
      keyword: "ELM 3"
      calendar_id: "9a901e48af79cd47cb67c184c642400a25fc301ad3bacf45ae6e003672174209@group.calendar.google.com"
    timetable_2:
      url: "https://nbl.hsbi.de/elearning/webdav.php/FH-Bielefeld/ref_155901"
      keyword: "ELM 5"
      calendar_id: "dd947828be3d70701a1373643ece5ef5bee930d44c14fa2bf7ba3dc9004d603e@group.calendar.google.com"

# --------------------------------------------
# Google Calendar Configuration
# --------------------------------------------
google_calendar:
  auth:
    token_json_file: "config/token.json"
    credentials_json_file: "config/client_secret.json"

  # Time zone setting for Google Calendar events
  time_zone: "Europe/Berlin"

# --------------------------------------------
# General Settings
# --------------------------------------------
general:
  # Dry run mode flag.
  # - true: Simulate actions without making actual changes.
  # - false: Perform real updates to Google Calendar.
  dry_run: false

# --------------------------------------------
# Output Settings
# --------------------------------------------
output:
  download_dir: "./downloads/"
  output_dir: "./output/"
